language: node_js
node_js: 
  - "6"
sudo: false

branches: 
  only:
    - release

cache:
  directories:
    - node_modules

script: npm run build  
after_success: 
  - git config user.email "nandenjin@users.noreply.github.com"
  - git config user.name "Robot Builder"
  - git fetch origin master:master
  - git checkout master
  - git add .
  - git commit -m "Build for ${TRAVIS_COMMIT} by Robot Builder"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/nandenjin/nandenjin.github.io.git" master:master > /dev/null 2>&1